services:
  attendee-worker-local:
    build: ./
    volumes:
     - .:/attendee
    networks:
      - attendee_network
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_URL=redis://redis:6379/5
      - DJANGO_SETTINGS_MODULE=attendee.settings.development
      - SECURE_PROXY_SSL_HEADER=HTTP_X_FORWARDED_PROTO,https
      - CSRF_TRUSTED_ORIGINS=https://attendee.rimthan.cloud
    command: ["/bin/bash", "-c", "/opt/bin/entrypoint.sh && celery -A attendee worker -l INFO"]

  attendee-scheduler-local:
    build: ./
    volumes:
     - .:/attendee
    networks:
      - attendee_network
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_URL=redis://redis:6379/5
      - DJANGO_SETTINGS_MODULE=attendee.settings.development
      - CSRF_TRUSTED_ORIGINS=https://attendee.rimthan.cloud
    command: ["/bin/bash", "-c", "/opt/bin/entrypoint.sh && python manage.py run_scheduler"]

  attendee-app-local:
    build: ./
    volumes:
     - .:/attendee
    networks:
      - attendee_network
    ports:
      - "8023:8000"
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_URL=redis://redis:6379/5
      - DJANGO_SETTINGS_MODULE=attendee.settings.development
      - SECURE_PROXY_SSL_HEADER=HTTP_X_FORWARDED_PROTO,https
      - CSRF_TRUSTED_ORIGINS=https://attendee.rimthan.cloud
    command: python manage.py runserver 0.0.0.0:8000

  postgres:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_DB: attendee_development
      POSTGRES_USER: attendee_development_user
      POSTGRES_PASSWORD: attendee_development_user
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    networks:
      - attendee_network
    restart: unless-stopped


  redis:
    image: redis:7-alpine
    networks:
      - attendee_network
    restart: unless-stopped
    volumes:
      - redis:/data/redis

networks:
  attendee_network:
    driver: bridge

volumes:
  postgres:
  redis:
